server:
  port: 8080
springdoc:
  packages-to-scan: "ru.shift.budgetplanner"
  paths-to-match: "/**"
  api-docs:
    path: "/api/docs"
jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
